[[cufinufft]]
arch = "x86_64"
cuda = "11.4"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7f02036305056338aaabfc14ef45baece62b95d"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "55943fe8238f7f16eb7b3f63a4ac7ce7f3fbd37ee283fd981264cc73ccd061cf"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+11.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5fdb875dab37d7bf883fbd5133e2e6fb3ee2b53"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "849c5e25fc24570aa35eec83c5b04a997a4330c4131f1229d3cc4880d168ee02"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+11.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.5"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a9a965a3b03b11d64f0cb195f4844384c86a549"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "758c284dd85cfa543645afd22b58077d26d5515665a31269fb743d45db359e89"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+11.5.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cc93f9ad44c4d67a49d16958ee9cc7b5712d029"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "4d4c2ee2eba5b77c86929a49738718deb8c0c2f58a4e9e8cb83ea461a2603426"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+11.5.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.6"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70a5617dbc88d61d8e2f19dcb7b7b2012869edf4"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "87c1feea06687fc43c91e4be5e2a2b7b646ca52059ddcd22f20ad2546d26435b"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+11.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c94c0f5bd18df9d28fde59f4c6c7efd91821282"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "727654d035ecd29338c4fe186e91ee7566fb61f03aebfd69374ac445bf73c393"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+11.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.7"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96081ffb09326a355f245279bfaae341293c2b11"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "51fbde7662daecd31719d5bed2e2eadea1a65ced98bbfe373ad0299f2069541f"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+11.7.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.7"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9b1090ab83a5819ec0c1eaf35979f7a082d24f2"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "9a17723089aaa370e3ee2bf4f19a42b9acfa9953504273dfc1cd00d59533bd3f"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+11.7.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.8"
cxxstring_abi = "cxx03"
git-tree-sha1 = "728cae9c746fa60827d1ae8b71120fd6cecbeada"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "065836c6f421fa65e5d448d82365f90b8d8c5f59c2fa3ee9d001e445d801df74"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+11.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "918edd45e820c29c6c511a399293ed61d84f5e75"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "0a09b4f6d6a7079dcedac4aae7323e18dc8f7f38ada521c5e24ab4bca134a508"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+11.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e31a29ef89f8a623d91e479b1d703714c61b59f"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "0babdeab8da61d8d608aaa80b8f5c16a94a8edfe48f6ec079e90f4afb815acf1"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.0.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98041fa46276aa54b1d520bb063de61bca2a925e"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "5f0648b42747d484779abd18b00af33dc076f75e3ab247488497019965dd870a"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.0.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.1"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69ce8c9e610ff536173b34f6269ef6aee9334daa"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "e1279f5bea52ea6e4837553d52d06537310e8bea85654b59c43f18f4c2174477"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.1.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.1"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5599a0c3f7d345a64abf6edbd222d7cee63e449"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "9445a2b172f40a3f504ca145862a26d5f36012c2d445e48eafd4ca13f1903fbd"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.1.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6e71933e340f21372866bcb2a3fb4a96ed605cd"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "3c4a5f892d7146317b38cfd09549522c29d9d7bf121560f1aa8f6fb54129aed8"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.2.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "324ff04529e2ce59ef9be1d2edc3d12420aa665b"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "4d728b2618cd080e60662ca118ea02070d7fc08b4b6388bff724b6c6fb918850"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.2.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f714467ac82f5693c28028b546445b6b83562c0"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "db8b89af788f41ad0d2f595fec79b6d59b6fd542463f43e1f886e59f29a29048"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.3.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c15c976b6326eadf6cf2dfe9800715f0082dd23b"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "073cf94cb7849418bbe9463b1a0915f0f805d47e98f33b81eb3f41eb90750941"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.3.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ffcbd6b6a9c440966b0f5740068006c3d92c650"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "7329fce751e46cfd99302433026763228d9f2b078141c505dce9f082fc6b3efe"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd9ddc6211d0ec48721cdaa93366c6c603fe7333"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "07ddc6d09b2c8ff067fba0b0d6e8f81433f85f2a62d9042cc111e6c7be10bcda"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efb224b2f75ab4b6c5b1e785e81d50396bf95625"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "755f74ad95a7f0301af6f990e051dd3fdb7aa68d5cf75ccdaad8c80640609c09"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55b612fa7b9b34e400045bc8dca6f863d429fc78"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "3b031e0aa02c7370c7b66d232e5262e758742b107fe7f99bd97a140e0d3e657c"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63a230db12ff7edff6a976f34bea1943c8f24178"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "847cdc84b8e23e68c74a57ba70e87438182c00d905a88267a2d8e90eb2585f42"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a612f529ae32ce39c486c94690b894eb509c0ac"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "bdfd00e280e2d7ebe01fdd1aa9dd5b376aac984613a189118b39e85d838dd9e3"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+0/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.8.tar.gz"
