[[cufinufft]]
arch = "x86_64"
cuda = "11.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e80c53965c033627c8460258ea0b467b28c2c6e0"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "606f6b3a1f75905a84466235d994fca7c88d38fad3aa0872103d6f436f2e1eed"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+11.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1ede0728b05efea2bb25651407ac8db991d07b6"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "c7390daa930349b0e9cc74da9ea2cb17c96023758f1d06ffa90f470c27ec0ad2"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+12.0.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.1"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a5ddefbaacc33c007a8a1c8562c10d44db49a2e"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "4dff49e1bb1deb4a28b904c6c9970b01f62e677c8f129bf2b41a070a0840ec29"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+12.1.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "142562299725f25b451e7303689cc4484c04082b"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "53ad704eda6de92c80cbbd16c9ed3daaa04996a7693c6f2ea99e0efa1f4f754c"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+12.2.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0706aa5178866313f1a805d10b17821c4b869c4b"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "55087221ccddc0b5d3305a823025fe7b1e64ab321f243b27afc8510186800f61"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+12.3.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c262b3066597a4cb74112fb2c8a80cab4621d52b"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "a544cbd8614a8c50b5d6e5cae3325c58be0ebe5c159fe81d8cc1809fb0acf943"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+12.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "195f1c9fcab81642f555189c351f059676ed496d"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "c2481912382b4dfb4f3bf03c11cbf449c82eb3834115a1e2c1938b3fdd1e5d13"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+12.5.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9197663c0dee975139ea921c4f53abc238d618e1"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "90368d2d5b41591a76ffdfcc72ec21c28df7e9c4c1089f1acce610cc5f1591c2"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+12.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc1730f68e8b7ca47b1abee38ba123327919542b"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "323365d8a152743be96bde8d5554dcfa56b2f3bb9041f22a255bcee832f63a84"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+12.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.9"
cxxstring_abi = "cxx11"
git-tree-sha1 = "064fc4ecdf43186731fc4cb6c43426e968f063c2"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "fc3d1e7f199f156be3989aac9a2f44f220739f35e8bca99466494b38f0ab5434"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+12.9.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf59487c3f8eac33cdeb880f28631a7f16fda96e"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "b10b3443dcd71e5415092eec934fa6e59d43f130f7a7213afa6b153c72bb98fe"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+13.0.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "13.1"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73004f86c3b64fc101f34fc94924f427fe0503b0"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "727e8f4d6f413ee16a628b2f010f07e9e44c4a1a73316b68288bf7ebf7a0458b"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.0+0/cufinufft.v2.5.0.x86_64-linux-gnu-cxx11-cuda+13.1.tar.gz"
