[[cufinufft]]
arch = "x86_64"
cuda = "11.4"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50d1b94fcc99ef6a7f3b9bac55a0c012c34a940a"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "a0111d1ad54a32a70d1ec828469347a59c9a3afa2123da6d12a06bc2a1cd217a"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+11.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2ceecb1564abd52fb491b787fb2e92c62a9d904"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "31824c8a3c30b6f7ff11566817a935814e1d2e5587b30549d607a59042fc41f3"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+11.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.5"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8603a5bf41e1d043b6f13cc21a8818786c47efb"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "6bf79877644225d11e2e5e5da381c734fc024846ae9e1cf71faf236e9b0f39eb"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+11.5.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dc453e0b5d302755cceec01f1fa6ebe3586c775"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "2dd61a7a0c57f748b18826235033d211094212df92c09916ca1a1bcdc5350b5b"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+11.5.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.6"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c3906d534ec66ccbcdf594ae72c21865864cae2"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "d55954188cf7a6241168e1773406e32a9972ad8992bdbab2f7ec5fafae7814cb"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+11.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac71e8cb986100d84f5e477f85023435b0264420"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "9b21574754d3dcddd78ac573886a74699616f20f1be3dc65a6a4530553dfdc3f"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+11.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.7"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b486c2ce31f01d0788cf9080f82d66a5347ab9e5"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "d07abdcfcf230986b6b7b3566d47229918037a18cb81eb0328e65c476074e23e"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+11.7.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.7"
cxxstring_abi = "cxx11"
git-tree-sha1 = "932e5fd2b9280aa3c29783bbbc8a26abd9b0662a"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "989b198c3852e7d85fed3fcc5e13573c549392b4b61b104f9590b65f8de2edca"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+11.7.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.8"
cxxstring_abi = "cxx03"
git-tree-sha1 = "287456b994372e4ba38cffc0f4c60179060699d3"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "d0e5ed01512663578696415ebe666e14fed56bc721dc86f51f408e140d8c7dfc"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+11.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3b7bed8feaecf913b19e72efe3a49b81d93f956"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "0305cb306c9e9c089fdcf124a0d2a884a743eb319bcc5d53c687534057098d16"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+11.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ceb1d90dbc1a8a5109a8b4a5a1d74b855a53ad95"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "d65e3810ce7b33fa29b8620f0afbc23e8a6250ae864a541d65077de3d8daf245"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+12.0.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee69eed0bf6bca03cc1a2da7eab4ceac3d1176a5"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "d3033e1aabe07d2e47f7eaacd766d586eda1cb47851994f0993839500d2e41e2"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+12.0.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.1"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2dfea9f404da783998ae3110c81cf7347800af2"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "32fcc115949ddc2c0f9bc6cf2f2ce09c1f9a59a3122aae93e787de635a075aab"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+12.1.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.1"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e907dd07db90a4b79e04d86a5cefbde68d54cfbb"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "8d7696dd16ff1751cbbf2ec4ce7d5a455895383e5006a313bc7003feff43a609"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+12.1.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbb55aca2e9f332aeff8d7a5a7fe07ffd9450ccd"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "0c669a265f77987b543b7ec71317edf82b7de74e5837222261ae58ec447ebac0"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+12.2.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18b1d00c1dd83d28e90dd7145321a63d119b0c42"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "d2fa0a9fc0f6634a53d90d23972c2407b9e395e1fa170795e2c0a38d5f925767"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+12.2.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fdc53f75dfe099bbe2b1674c1c0fcd9d6a6c17f"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "54bad4b2413c585928a88d1d97cf94e4560b15342a402453a6286654deed826d"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+12.3.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b33b91f810a065075d916ecfd4d9668b204fdb3d"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "11fdc1940031123cdbf84b2aaeb22b0438e1458adc9b89852bc2c4df5587aa0d"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+12.3.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ef0aa9bf12ed7290716f8f36d8263a66aab018a"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "0a6a404a49f9ed0276625e4661a0fffa6b3f0af96338696871a6dc5d48c6ecf1"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+12.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa2b1aaa880d791267a86cb5b1b5990b0b467295"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "ac43a4bf495cb61fc420ba72a7bf5c6066348a64ef66c5358971393fe4f64210"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+12.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.5"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0352d494cc14d2ae9252bd29bbd1e0e768a797c6"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "8c667d61db9e4fdc6b94ee404b949ab71391ba8674c7c73f4b95b787a0f115ae"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+12.5.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e71fef0d30b44a7f13b2b1f2c317f8e36b49f871"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "74f1c1326b11fb35017cc3e0779160d3f1c4d1fffebd3308077560379bd5a125"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+12.5.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx03"
git-tree-sha1 = "974fd295f0edb9b328b461221d043d8abd29ffbd"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "e632dabe280820d79ccb702618804e415d312aaa4e32ea0dd91ad7ca34c62484"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx03-cuda+12.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d8b66e2e9f7ad146bbf8005514dc4373afdb00b"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "093679fc18f1f5095d6c6a5d6e8a908b6b1f5a5e56cba797f6fa6a4a99894ae3"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.3.1+0/cufinufft.v2.3.1.x86_64-linux-gnu-cxx11-cuda+12.6.tar.gz"
