[[cufinufft]]
arch = "x86_64"
cuda = "11.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c7234d0181516810aa29ff6455517051d5f4f7c"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "0c12587634ec20161dd0bd15b3873e3767b38bd06f76b33f2ebfd1e7cc519c7a"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+11.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9c35563260b54f64dbb040cef4ac4d02847a731"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "1ff4ab6da042599c2bf417500094fd14354864920044c7595c8346c6fb42dbda"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+12.0.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.1"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1c68bb60cfabad519f3a101c222d36f034168ba"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "b6f8400680a13196d54b548f4dc486e18008f844eafe924d6d45314bccd3735d"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+12.1.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5089b69240299068abc1a91c864b3218fe8161b5"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "c627201b5dbef43f54f092f2784ddad743c230c7e7bbff28ba291e15a16843eb"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+12.2.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dfd9c22fc71abddc06fb877cfa96c0dc38dd285"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "6d5a581bd342ace708af0f56753060b704d1e2773da40d5bfb6edceaf44b6203"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+12.3.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79de449f195351bf1342a4c2601016c65fdb4ca1"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "89190a1497f4c2ad4de4b0fab05536ea678fef93dc7dff4176369d019796e043"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+12.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adcdb62d70a242e197c9f8c935da6aa53c22dc2d"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "4c2e3a25817008eb9d8cf6398ff4d5007d9f136fcfbe51a4768ae96fb28cd1ff"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+12.5.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb0d2e32140ef472dfdae316004405cbe5f9a898"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "ad4890114810db66b77c508accbf32fa21831314e2514d508d47c7e73ef48246"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+12.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ffc1a886f2f919dae8ef5ac67c55893a3d4f561"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "4e7ff4bbff8b79ff1c062ee56aca1d95d4b2ef4d3b260501f50a069e6c0e553c"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+12.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.9"
cxxstring_abi = "cxx11"
git-tree-sha1 = "493974a3bab2b980896e0fcc5f1f91dbf2e02fa8"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "43e5e149f3970c8473026606a35798e1a2416667ba666de69ceb1a5d53ab4f63"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+12.9.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb6f0729b65594650b35e9566e2ecd624a4a16a4"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "3de28bb36f8e3fbff1d3ded4810ca3abac45ea22f6730a78031090cb35d35a52"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+13.0.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "13.1"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e2caa4d94e76253471d6d8b22655b961f8f3943"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "bdf63452c5614e88f058b5da07693cb702068db5fba497770b23e16dc68c0c15"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+13.1.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "13.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bb08e97e9283e5e8075b68c5c73de59b8d3826c"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "5f6f9f81bc44dae903a127b2000a8c139a1551914819b42f14774e06209561cd"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.5.1+0/cufinufft.v2.5.1.x86_64-linux-gnu-cxx11-cuda+13.2.tar.gz"
