[[cufinufft]]
arch = "x86_64"
cuda = "11.4"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db7006036355c08ab5fb674b74f3dcbdd530e6b6"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "cfa908c9d8a66274865d96669b20715a759fcdc07e3ade75a38b9de328fd68ef"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+11.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2859965e1c723824bcc449e32360f3a45cb0529f"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "62e44d20492da83bbb20afffe81d32647cb2a912393dce22b0e4cd6e52396e13"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+11.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.5"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96ce7c5a7f1c203d5d27d8d9764c4bb2b7041d60"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "4e288bd3a97f421a21ff1547173be1f652f6269b55b1bd9fe3f9f5b6582b8f7b"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+11.5.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0227b9c5643690eacb7645c64e21613a002f7b52"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "5254ac98db7356a5f207fa17e5b128a4c25f93ac2b699285d7af05b12dbc5faa"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+11.5.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.6"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0026884d439b8990b3be8a3f2ff079235fdb4ef6"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "f84519b2b9d97fb305dbc28ace83f3f2e4e57529bca7d937cf81857cdee3d1c6"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+11.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e201054b4f481ac64f8ceebe0d7e182490b96378"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "07aaadf6560c27b0f6495e0b91df2a0a812490efe9d268d7c833613c32c3a0bd"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+11.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.7"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a96d80c469aa67516f9a24864e0027c40a834ed"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "d92595d7f94abff68d6d65cbd0a63b1c931995c4f8cec713dae254674c495595"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+11.7.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.7"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d8618b07d5d32aa794d9ee537dbcf7c7838e500"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "cc9d77391627b30128a29896ae8eab45bf551a228d3ddacb67de4f09e6ada9e9"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+11.7.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.8"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb01a8f9684d0032bec427b6d95c35659afcdb4b"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "587353e8ca23b9c827099d147330a822a4a32d5b2c501a1252cdefc229722d5b"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+11.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "11.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "644b0869b3d8beacac59a7eb5e7faebf23d29de7"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "cfbdad3bd7f425a47e160d7d56aa8934142ce8c04a0d092dc1b233b673eb57f5"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+11.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx03"
git-tree-sha1 = "198bc6964ac856297ff815bf4873e1a6082fb9d2"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "f73e95a87e4c6ab5842f5534a9a29662a78b8655b0423be252c15f7c9cb5939d"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.0.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3429db1f609a1dd33c6356d238363c3248017ce"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "a0bd0a7dfa8204acaad71a5dd6ce60bb298a085de77a488c4329db7bc2599a82"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.0.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.1"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9ebc40e9f8148e5ce87ca25493e8948e32a7870"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "879fe62f234bb1fc9c547b7c3a8d58cf15d1fd5863993102c30b6a948459d7f8"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.1.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.1"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1086b62aaa9661532d913e984d4d8b48a106f8c8"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "0e5b05a58dfdc8aa48085f9f348698bd08653bacbe50c00ed39f2c314a5ba2a5"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.1.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31942e4b1b73b22dada61dabc82ff1d7998dd608"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "328a5374f263e44b0b95a786f2dc7bd732145b13bb52cab57b443178058ec6b1"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.2.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be343083395c1c4dd2bfd3c076dd8df44849217e"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "47aa2d5fcc3dd54dc221868725e3b79b382443d1a05267ff9e5356a6ac0ec23a"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.2.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx03"
git-tree-sha1 = "990758704e127c12ca77460f647bdaa1b777f58e"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "3d308fa193d9eac1ef95f9d97c78810f9b9be9ac20bc525c59cafc858244be44"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.3.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e72ba22c444d75af458f268a6c7c3793fcb3af15"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "81077d5d8e89d8feaf20d7afb31205edeb540c98ba1e921f7f3d5a84484c8e7a"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.3.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cd36a38d5fb6502d284682f8adabb89f1d5b96d"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "922c3fd649bc23956a8a0ddc411d8797a819cdb6ef7a4198b1bea09a254a0163"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbae2785fafa11ac97825ff30f95ba1858fa64dc"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "968e18e3dc2e3ea5e332941b85a78cb55ed651c1d883504b460f129232f5691e"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.4.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f0bfbfb77ff28dab4c94918944379902a3c5ac0"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "256d9b75070987e24a4dfba73b600dce337fb2d66c4ec7033ff34e297be13189"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f848aea842766736d342628771d78be70f9e8bc7"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "eaf84742bff13d612a67964b607d5eb49a2104aeb8e3abda5ab66ee0897434c3"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.6.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx03"
git-tree-sha1 = "325a8d4b9f3a265eb40a01cb1b9de395e8cc3ba9"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "32f8d7559e23ed8d881596c2ba9b371db85d6aae510c348fd2da72657d639d92"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx03-cuda+12.8.tar.gz"
[[cufinufft]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0fb844fcb97351d0e1abc909579783c321c1a8d"
lazy = true
libc = "glibc"
os = "linux"

    [[cufinufft.download]]
    sha256 = "1eca49c0097c34fb5542b92388d6878c8cbb18015b4626604e02f139d0e46981"
    url = "https://github.com/JuliaBinaryWrappers/cufinufft_jll.jl/releases/download/cufinufft-v2.4.0+1/cufinufft.v2.4.0.x86_64-linux-gnu-cxx11-cuda+12.8.tar.gz"
